name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Node.js app
        uses: appleboy/ssh-action@v0.1.2
        with: 
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            mkdir test
            cd test 
            git clone https://github.com/tavistoica/RandomThoughts.git
            echo 'Deployment completed!`
